services:
  # Nosso "Correio" (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: auth-bot-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - auth-bot-net

networks:
  auth-bot-net:
    driver: bridge